name: tech_express_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  delayed_display: ^2.0.0
  lottie: ^1.1.0
  unicons: any
  tab_indicator_styler: ^2.0.0
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  awesome_dialog: ^2.2.1
  dependencies:
  qr_flutter: ^4.0.0
  uuid: ^3.0.6
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: ^0.6.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_credit_card: any
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/icon.png"

  android_12:
    color: "#ffffff"
    image: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/
    - assets/images/
    - assets/pngs/
    - assets/images/companies_logo/
    - assets/images/seats/
    - assets/lotties/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    #         style: italic
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Barcode
      fonts:
        - asset: assets/fonts/LibreBarcode128-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
